plugins {
    id 'com.android.application'
}

android {
    namespace 'com.jarvis.assistant'
    compileSdk 34

    defaultConfig {
        applicationId "com.jarvis.assistant"
        minSdk 21
        targetSdk 34
        versionCode 7
        versionName "3.2"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    sourceSets {
        main {
            manifest.srcFile 'src/main/AndroidManifest.xml'
            java.srcDirs = ['src/main/java']
            res.srcDirs = ['src/main/res']
        }
    }
}
